eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    
spring:
#  application:
#    name: SERVICE-REGISTRY
  zipkin:
    enabled: true
    base-url:  ${ZIPKIN_SERVER_URL:http://localhost:9411/}
#  profiles: docker
#  config:
#    activate:
#      on-profile: docker



#server:
#  port: 8761


management:
  endpoints:
    web:
      exposure:
        include: *


