eureka:
  client:
    service-url:
      defaultZone: ${REGISTRY_SERVER_URL:http://localhost:8761/eureka/}
#    register-with-eureka: true
#    fetch-registry: true

#    server:
#    waitTimeInMsWhenSyncEmpty: 20
#  instance:
#    hostname: "service-registry"
#    prefer-ip-address: true

spring:
#  application:
#    name: SERVICE-REGISTRY
  zipkin:
    enabled: true
#    base-url:  ${ZIPKIN_SERVER_URL:http://localhost:9411/}
    base-url: http://zipkin-server:9411/
#  profiles: docker
#  config:
#    activate:
#      on-profile: docker

  banner:
    location: classpath:banner.txt

#server:
#  port: 8761



management:
  endpoints:
    web:
      exposure:
        include: "health,refresh"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


