#eureka:
#  client:
#    service-url:
#      defaultZone:  ${REGISTRY_SERVER_URL:http://service-registry:8761/eureka/}
#    register-with-eureka: true
#    fetch-registry: true

spring:
  application:
    name: GATEWAY



  cloud:
    gateway:
      routes:
        - id: service
          uri: lb://SERVICE
          predicates:
            - Path=/red/**, /blue/**
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/user/**,/auth/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - AuthenticationFilter  


#  zipkin:
#    enabled: true
#    base-url:  ${ZIPKIN_SERVER_URL:http://zipkin-server:9411/}

server:
  port: 80

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
