spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.11.200:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: *
#              packages: com.ssl.productservice.dto.ProductEvent





server:
  port: 8087



logging:
  level:
    root: INFO
    org.springframework.data.elasticsearch.client.WIRE: trace
#    org.springframework.web: ERROR
#    com.demo: DEBUG
#    org.hibernate: ERROR





