eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  ${REGISTRY_SERVER_URL:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    
spring:
  application:
    name: CONFIG-SERVICE
  zipkin:
    enabled: true
    base-url:  ${ZIPKIN_SERVER_URL:http://zipkin-server:9411/}

